# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

# 23010101226 - Drashti Rathod - 516

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [5]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

1D Array: [1 2 3 4 5]


In [9]:
arr = np.arange(10)
#arr = np.arange(10,20)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Step 3. Reshape 1D to 2D Array

In [11]:
arr1 = np.arange(20).reshape(4,5)
#here 20=elements and 4=rows & 5=columns
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Step 4. Create a Linspace array

In [15]:
np.linspace(4,8,25)

array([4.        , 4.16666667, 4.33333333, 4.5       , 4.66666667,
       4.83333333, 5.        , 5.16666667, 5.33333333, 5.5       ,
       5.66666667, 5.83333333, 6.        , 6.16666667, 6.33333333,
       6.5       , 6.66666667, 6.83333333, 7.        , 7.16666667,
       7.33333333, 7.5       , 7.66666667, 7.83333333, 8.        ])

### Step 5. Create a Random Numbered Array

In [21]:
arr3 = np.random.rand(7)
arr3

array([0.97479339, 0.05418673, 0.58321385, 0.39446954, 0.10790971,
       0.24822399, 0.91017749])

In [23]:
arr4 = np.random.rand(2,4)
arr4

array([[0.21311321, 0.64573527, 0.47604952, 0.40916738],
       [0.03643327, 0.58943059, 0.64446462, 0.31507212]])

### Step 6. Create a Random Integer Array

In [27]:
np.random.randint(10,50,size=10)

array([22, 40, 12, 40, 32, 47, 19, 27, 12, 30])

In [29]:
np.random.randint(10,50,size=(7,5))

array([[41, 10, 45, 49, 33],
       [46, 29, 24, 23, 48],
       [49, 32, 38, 21, 43],
       [18, 13, 13, 45, 18],
       [33, 46, 37, 28, 30],
       [38, 26, 20, 24, 16],
       [14, 20, 42, 24, 42]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [35]:
arr5 = np.random.randint(20,60,size=7)
arr5

array([41, 39, 21, 46, 22, 28, 52])

In [37]:
arr5.max()

52

In [39]:
arr5.min()

21

In [41]:
arr5.argmax()

6

In [43]:
arr5.argmin()

2

### Step 8. Indexing in 1D Array

In [45]:
arr5[4]

22

In [47]:
arr5[3:6]

array([46, 22, 28])

### Step 9. Indexing in 2D Array

In [49]:
arr6 = np.random.randint(10,50,size=(7,5))
arr6

array([[29, 31, 31, 38, 45],
       [32, 34, 25, 15, 31],
       [39, 23, 26, 46, 23],
       [23, 43, 12, 15, 15],
       [37, 41, 20, 46, 15],
       [25, 32, 35, 32, 30],
       [32, 11, 17, 47, 38]])

In [53]:
arr6[1,1]

34

In [55]:
arr6[4]

array([37, 41, 20, 46, 15])

In [59]:
arr6[6][2]

17

### Step 10. Conditional Selection

In [61]:
arr7 = np.random.randint(20,40,size=10)
arr7

array([32, 34, 25, 21, 26, 35, 34, 36, 35, 21])

In [63]:
arr7[ arr7 > 25]
#arr7[ (arr7 > 25) & (arr<35)]

array([32, 34, 26, 35, 34, 36, 35])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [65]:
import pandas as pd

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [71]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
users

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [77]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|", index_col='user_id')
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [73]:
users.head(25)

user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [75]:
users.tail(10)

user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [81]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [83]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [85]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [87]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [89]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [93]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [101]:
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [103]:
users['occupation'].mode()[0]

'student'

In [107]:
df['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [109]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [113]:
users.describe(include='all')

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [115]:
df['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [119]:
users['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [125]:
users['age'].value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

In [123]:
users['age'].value_counts().min()


1

In [127]:
users['age'].value_counts().idxmin()

7

### You're not just learning, you're mastering it. Keep aiming higher! 🚀

In [134]:
print('Thank You')

Thank You
